# Generated by Django 2.2.13 on 2020-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Condition',
            field=models.CharField(blank=True, choices=[('', 'Please choose if possible'), ('As New', 'As New'), ('Very Good', 'Very Good'), ('Acceptable', 'Acceptable'), ('Mixed', 'Mixed')], max_length=50, verbose_name='Condition of book(s) (optional)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=590, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Image 2 (optional) '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Image 3 (optional) '),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0.0', max_digits=6, verbose_name='Price (kr)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
