# Generated by Django 2.2.13 on 2020-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0002_auto_20200721_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('new_group', 'new_group'), ('new_group1', 'new_group1')], default=0, max_length=50, verbose_name='What group do you want to publish to?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='post_pics', verbose_name='Image '),
        ),
    ]
