# Generated by Django 3.0.8 on 2020-07-27 10:08

import bookmarket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0003_auto_20200725_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='post_pics', validators=[bookmarket.models.Post.validate_image], verbose_name='Image '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='post_pics', validators=[bookmarket.models.Post.validate_image], verbose_name='Image 2 (optional) '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='post_pics', validators=[bookmarket.models.Post.validate_image], verbose_name='Image 3 (optional) '),
        ),
    ]
