# Generated by Django 2.2.5 on 2019-09-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Condition',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('as_new', 'As New'), ('very_good', 'Very Good'), ('acceptable', 'Acceptable')], default=('uns', 'Unspecified'), max_length=50, verbose_name='Condition of book(s):'),
        ),
    ]
