# Generated by Django 2.2.5 on 2019-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0003_auto_20190911_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Additional image 1 (optional)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Additional image 2 (optional)'),
        ),
    ]
