# Generated by Django 2.2.5 on 2019-09-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0005_auto_20190924_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Condition',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('As New', 'As New'), ('Very Good', 'Very Good'), ('Acceptable', 'Acceptable')], default='Unspecified', max_length=50, verbose_name='Condition of book(s)'),
        ),
    ]
