# Generated by Django 3.0.8 on 2020-07-29 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarket', '0005_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'general')], default=('general', 'general'), max_length=50, verbose_name='What group do you want to publish to?'),
        ),
    ]
