# Generated by Django 2.2.5 on 2019-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0006_auto_20190924_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Condition',
            field=models.CharField(blank=True, choices=[('', 'Please choose if possible'), ('As New', 'As New'), ('Very Good', 'Very Good'), ('Acceptable', 'Acceptable'), ('Mixed', 'Mixed')], default='Unspecified', max_length=50, verbose_name='Condition of book(s) <small> <br /> If you have multiple books of varying conditions, choose "mixed" </small>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='SellerOrBuyer',
            field=models.CharField(choices=[('Buyer', 'Buy'), ('Seller', 'Sell')], default=('Buyer', 'Buy'), max_length=50, verbose_name='Are you here to buy or sell? '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics', verbose_name='Image '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Additional image 1 (optional) '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Additional image 2 (optional) '),
        ),
    ]
