# Generated by Django 3.0.8 on 2020-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0006_auto_20200729_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A-sek', 'A-sek'), ('All', 'All'), ('E-sek', 'E-sek')], default=('A-sek', 'A-sek'), max_length=50, verbose_name='What group do you want to publish to?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=6, verbose_name='Price (kr)'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
