# Generated by Django 2.2.5 on 2019-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0007_auto_20190924_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Condition',
            field=models.CharField(blank=True, choices=[('', 'Please choose if possible'), ('As New', 'As New'), ('Very Good', 'Very Good'), ('Acceptable', 'Acceptable'), ('Mixed', 'Mixed')], max_length=50, verbose_name='Condition of book(s) <small> <br /> If you have multiple books of varying conditions, choose "mixed" </small>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=6),
        ),
    ]
